services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend-network
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: webAI
    restart: unless-stopped

  backend:
    build: ./backend
    image: igorushakov05/hunt-ai-server:v0.0.1
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build: ./app
    image: igorushakov05/hunt-ai-client:v0.0.1
    container_name: frontend
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  backend-network:

volumes:
  mongodb_data: