services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: webAI
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "mongodb://root:password@mongo:27017/webAI?authSource=admin"
    networks:
      - backend-network
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./app
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    networks:
      - backend-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo-data:
  mongo-config:

networks:
  backend-network:
    external: true