services:
  backend:
    build: 
      context: ./backend
      target: build
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "mongodb://root:password@mongo:27017/webAI?authSource=admin"
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./app
      target: prod
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    networks:
      - backend-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  backend-network:
    external: true