services:
  frontend:
    build: ./app
    image: igorushakov05/hunt-ai-client:v0.0.1
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    image: igorushakov05/hunt-ai-server:v0.0.1
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mongodb://host.docker.internal:27017/webAI
    extra_hosts:
      - "host.docker.internal:host-gateway"
