services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: webAI  
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - backend-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "mongodb://root:password@mongo:27017/webAI?authSource=admin"  
      SERVER_URL: "https://api.hunt-ai.ru"
      CLIENT_URL: "https://hunt-ai.ru" 
    depends_on:
      - mongo
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build: ./app
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    environment:
      NODE_ENV: production
      REACT_APP_SERVER_URL: "https://api.hunt-ai.ru"
      REACT_APP_CLIENT_URL: "https://hunt-ai.ru" 
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  backend-network: 
    driver: bridge