services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "mongodb://root:password@mongo:27017/webAI?authSource=admin"  
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build: ./app
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    external: true
