name: Тестирование

on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Записываем .env 
        run: echo "${{ secrets.BACKEND_ENV }}" > backend/.env
      
      - name: Создаем сеть (если еще не существует)
        run: docker network create backend-network || true
      
      - name: Запуск MongoDB
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.mongo.yml"
          action: "up -d"
      
      - name: Запуск основного приложения
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
          action: "up -d --build"
      
      - name: Тестирование (добавьте свои тесты здесь)
        run: |
          # Здесь могут быть команды для запуска тестов
          echo "Running tests..."
      
      - name: Выключаю
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.mongo.yml down