name: Docker Compose CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        networks:
          - webnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker containers with Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for backend health check
        run: |
          for i in {1..10}; do
            if curl --silent --fail http://localhost:4000/health; then
              echo "Backend is healthy"
              break
            fi
            echo "Waiting for backend to become healthy..."
            sleep 5
          done

      - name: Run frontend tests
        run: |
          # Тесты для фронтенда, если необходимо
          curl --silent --fail http://localhost:3000

      - name: Tear down containers
        run: |
          docker-compose down

    networks:
      webnet:
        driver: bridge
