name: Тестирование

on: 
  push: 
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Записываем .env файлы
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env
          echo "${{ secrets.FRONTEND_ENV }}" > app/.env
      
      - name: Создаем сеть
        run: docker network create backend-network || true
      
      - name: Запуск всех сервисов
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-files: |
            docker-compose.mongo.yml
            docker-compose.yml
          action: "up -d --build"
      
      - name: Тестирование
        run: |
          # Ваши тестовые команды
          echo "Running tests..."
      
      - name: Остановка сервисов (опционально)
        if: always()
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.mongo.yml down